### ISSUE TITLE
ProxyFetcher::Client.get Never Returns

### ISSUE THREAD

**Issue by ishields** [nbulaj/proxy_fetcher#18]
This gem looks great but in attempting to use it I can't get ProxyFetcher::Client.get( 'https://example.com/resource') to return anything.  In my rails console it just hangs.   I'm able to manually create a manager and fetch a list of proxies fine but the Client.get just never returns any results.  Is there something I'm missing?

I've tried both the master version and release 0.6.3

**Comment by nbulaj** [comment]
Hi @ishields . Is it return blank string or nothing?

The algorithm of the ProxyFetcher client is as follows:

1) Load and validate proxy list (can take some time)
2) Try to load requested resource with valid proxy
3) If error returned (timeout, etc) - retry N times (`max_tries` option)

So if no content returned, than you need to wait, because Client is trying to load the resource from valid proxy (many providers can response with dead proxies)

**Comment by ishields** [comment]
So I've finally had some time to dig in and put some breakpoints in.  It does look like the request is failing and going into the retry loop.  

The error is caught here https://github.com/nbulaj/proxy_fetcher/blob/master/lib/proxy_fetcher/client/client.rb#L179 and it looks like it's a "end of file reached" error.  

This looks like it's happening here https://github.com/nbulaj/proxy_fetcher/commit/c9ad6cadaf18cabe92f562674ddbb924d68ea358#diff-56207f584317c1418c56049637daeb34L92

on the http.start.  It never gets into that block.  It does looks like you recently refactored this so maybe I should pull from master.  

I'm still able to make the request with 
```
open(url, 'User-Agent' => user_agent, proxy: proxy) 
```
but as soon as I use the ProxyFetcher client it fails.  Looks like these are two different ways of making the request.   

Have you tested that these examples from the readme work?
```
ProxyFetcher::Client.get 'https://example.com/resource'
```

**Comment by ishields** [comment]
@nbulaj I pulled from master and it works now!  I know you're probably still working through the refactor but I was wondering if you planned to change what the client returns?  Seems like right now it's returning a string.  I kinda expected that it would use the specified adaptor (Nokogiri by default) and return that parsed object.  Anyway - great work on the gem!  Really appreciate all your work!

**Comment by nbulaj** [comment]
Hi @ishields . Can you test it now?

> 2.4.1 :004 > require 'benchmark'
>  => true 
> 2.4.1 :005 > Benchmark.measure { ProxyFetcher::Client.get 'https://example.com/resource' }
>  => #<Benchmark::Tms:0x00000001bc4a70 @label="", @real=3.6560068419967138, @cstime=0.0, @cutime=0.0, @stime=0.0, @utime=0.0, @total=0.0> 
> 

It could be long, but I dont faced infinite request.

**Comment by nbulaj** [comment]
We have many improvements, especially for timeouts. Also we have a new backend for HTTP requests, so seems like this feature must be resolved. Ping me if it must be reopened
