### ISSUE TITLE
Proxy ".url" method does not return "http" or "https" as part of the url string 

### ISSUE THREAD

**Issue by ishields** [nbulaj/proxy_fetcher#19]
The documentation states that the .url method of Proxy "returns a formatted URL like http://IP:PORT" but it does not seem to actually return the protocol.  Looks like it's just "#{addr}:#{port}" .

**Comment by nbulaj** [comment]
Fixed in 5560e273dbbe9621ca66f420c1ecc4a278438e92 and added to docs, thanks!

**Comment by ishields** [comment]
Thanks for the quick response time!
